Cross/approximate site skeleton
feya-bilyzna/feya-bilyzna.github.io pull request #10
Opened 2021-07-03 15:01 UTC by AlecCross

Добавил файл со списком объектов (роут - пункт меню) для отрисовки через map() в NavbarMenu; 
Добавил компонент PageContainer  он берет страницы из routes.jsx и применяет к ним className='container'

2021-07-03 17:22 UTC, lifearoundfreaks requested changes
Помимо комментариев, когда запустил проект, была куча предупреждений, необходимо все устранить.

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/components/All-Types-Goods/ShapewearPage.jsx
> +            <GridTest/>
Просьба переименовать все компоненты со словом "Test" в названии в более адекватные. Потом это забудется. И останутся компоненты с такими названиями.

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/components/Main/Test/MediaBoxTest.jsx
> +            id="MediaBox_7"
Кажется, тут не нужен id.

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/components/Main/Test/ParallaxTest.jsx
> +                    <Button onClick={showToast}>Show toast</Button>
Нам нужна эта кнопка сейчас?

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/components/Main/Test/ParallaxTest.jsx
> +                    {/*<h2 className="header">*/}
Мусорные комменты.

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/components/Main/Test/ParallaxTest.jsx
> +            <div className="transparent">
Обсуждалось, что transparent не нужен.

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/components/Main/Test/PopoutTest.jsx
> +                // icon={<Icon>filter_drama</Icon>} //Не работает отображение иконки просто текст
Мусорные комменты в этом файле

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/components/NavbarMenu.jsx
> +                        {/*<li><NavLink to="/brands">Бренды</NavLink></li>*/}
Мусорные комменты.

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/utils/pagesList.js
> +const PagesList = [
Почему в утилсах? В утилсах обычно функции хранят, которые делают какую-нибудь работу с абстрактными данными, например.

2021-07-03 17:22 UTC, lifearoundfreaks commented on src/routes.jsx
>                  <Route path="/brands" exact>
Здесь также необходимо использовать PagesList.

2021-07-03 17:35 UTC, AlecCross commented on src/components/Main/Test/GridTest.jsx
> +            <Row>
Да, лучше отдельно

2021-07-03 20:11 UTC, AlecCross commented on src/components/Main/Test/CardImageTest.jsx
> +                lx={12}
Действительно, убрал.

2021-07-03 20:15 UTC, AlecCross commented on src/components/Main/Test/CardImageTest.jsx
> +        <Row>
Убрал, сократились отступы меджу рядами карточек по горизонтали, так даже лучше выглядит.

2021-07-03 20:45 UTC, AlecCross commented on src/components/All-Types-Goods/ShapewearPage.jsx
> +            <GridTest/>
Пока что переименую, но не уверен что правильно подобрал названия
Нужно будет подумать как лучше назвать некоторые компоненты. В процессе добавления функционала буду смотреть за этим.

2021-07-03 20:52 UTC, AlecCross commented on src/utils/pagesList.js
> +const PagesList = [
Переименовал в "data".

2021-07-03 21:04 UTC, AlecCross commented on src/routes.jsx
>                  <Route path="/brands" exact>
Использовал. Но в PagesList не все страницы. Например без Main и ContactsPage

2021-07-03 21:05 UTC, AlecCross commented on src/components/Main/Test/ParallaxTest.jsx
> +            <div className="transparent">
Я про неё забыл, так как не использовал всю компоненту.

2021-07-03 22:25 UTC, AlecCross commented on src/routes.jsx
>                  <Route path="/brands" exact>
Уже успел поломать...

2021-07-04 07:38 UTC, lifearoundfreaks approved these changes

2021-07-04 07:38 UTC, merged