Заменен материалайзовский слайдер на Swiper
feya-bilyzna/feya-bilyzna.github.io pull request #100
Opened 2022-07-04 17:27 UTC by AlecCross

![image](https://user-images.githubusercontent.com/49411370/177198285-baec0776-f819-4a33-8389-16921d7d0cc8.png)

2022-07-04 19:36 UTC, lifearoundfreaks requested changes

2022-07-04 19:36 UTC, lifearoundfreaks commented on src/components/Main/Slider.jsx
> +import 'swiper/components/scrollbar'
Точно не понадобится где-то еще на сайте? Возможно, есть смысл вынести в App?

2022-07-04 19:36 UTC, lifearoundfreaks commented on public/locales/ru/translation.json
> +    "А также примерить;понравившийся товар;- город Кривой Рог;- Центр-городской район;- улица Лермонтова;- Вещевой рынок;- ряд 2 - место 29": "А также примерить;понравившийся товар;- город Кривой Рог
Лучше не и использовать такие длинные ключи.
Когда текст для перевода длинный, можно в качестве ключа использовать кодовую фразу.
Для примера:
![image](https://user-images.githubusercontent.com/42870020/177208542-d78ad097-2f6e-4dec-9e2d-8af5ec4ab2b4.png)

2022-07-04 19:36 UTC, lifearoundfreaks commented on public/locales/ua/translation.json
> +    "А также примерить;понравившийся товар;- город Кривой Рог;- Центр-городской район;- улица Лермонтова;- Вещевой рынок;- ряд 2 - место 29": "А також приміряти;товар, що сподобався;- місто Кривий Рі
Коммент выше.

2022-07-04 19:36 UTC, lifearoundfreaks commented on src/components/Main/Slider.jsx
> +                    <a
По возможности, нужно использовать тут `Link` или `NavLink`.
В случае, если ссылка может быть и внутренней и на внешний сайт, возможно стоит проработать логику, которая будет делать разный рендер.

2022-07-04 19:36 UTC, lifearoundfreaks commented on src/css.module/slider.module.css
> +.slider {
Многие из стилей повторяются. Возможно, имеет смысл укоротить файл? И еще, в конце файла нет пустой строки.

2022-07-04 19:36 UTC, lifearoundfreaks commented on src/css.module/slider.module.css
> +    /* position: absolute; */
Стараемся не оставлять мусорные комменты.

2022-07-06 11:59 UTC, AlecCross commented on src/components/Main/Slider.jsx
> +import 'swiper/components/scrollbar'
Пока такой функционал не нужен (Уточнил у заказчика). Так что не понадобится.
Закажут, тогда будет смысл вынести в App

2022-07-06 20:15 UTC, merged