Реализация рендера товаров c бекенда
feya-bilyzna/feya-bilyzna.github.io pull request #14
Opened 2021-07-10 09:41 UTC by AlecCross

Реализация рендера товаров c бекенда, 
 а так же рендер категорий и подкатегорий на фронтенде;

Переходы из категорий в подкатегоии;

Некоторый рефакторинг в структуре файлов и их названий

Сменил в map() render значение для key prop с поля из объекта 'url' на 'name'

Видоизменил 'GridView' в 'CategoryGridView' и добавил 'ProductGridView'

Так же видоизменил карточки в 'CategoryPreviewCard' и добавил 'ProductPreviewCard'

2021-07-10 12:25 UTC, lifearoundfreaks requested changes

2021-07-12 05:39 UTC, AlecCross commented on src/components/index.js
> +export {default as linkListCategories}             from '../data/LinksToPages/linkListCategories'
"Вынес их"

2021-07-12 05:40 UTC, AlecCross commented on src/components/ProductPages/BraTypesPages/Foam.jsx
> +* import React from 'react';
Убран

2021-07-12 05:41 UTC, AlecCross commented on src/data/LinksToPages/linkListSubcategoriesBra.js
> +export default linkListSubcategoriesBra
Устранил

2021-07-12 05:42 UTC, AlecCross commented on src/components/Main/MainPage.jsx
> +                <h1 style={{"fontSize": "calc(24px + 16 * (120vw / 1280))", "textAlign": "center"}}>Группы товаров:</h1>
Изменил на Категории товаров

2021-07-12 05:46 UTC, AlecCross commented on src/data/ImageListsForCategories/imageListSubcategoriesBra.js
> +const imageListSubcategoriesBra = [
Переименовал imageListSubcategoriesBra  в braSubcategoriesData

2021-07-12 05:47 UTC, AlecCross commented on src/data/ImageListsForCategories/imageListSubcategoriesBrands.js
> +const imageListSubcategoriesBrands = [
Переименовал imageListSubcategoriesBrands  в brandsSubcategoriesData

2021-07-12 05:47 UTC, AlecCross commented on src/data/ImageListsForCategories/imageListSubcategoriesKnickers.js
> +const imageListSubcategoriesKnickers = [
Переименовал imageListSubcategoriesKnickers в knickersSubcategoriesData

2021-07-12 05:48 UTC, AlecCross commented on src/data/LinksToPages/linkListCategories.js
> +const linkListCategories = [
Переименовал linkListCategories  в categoryRoutesData

2021-07-12 05:48 UTC, AlecCross commented on src/data/LinksToPages/linkListSubcategoriesBra.js
> +const linkListSubcategoriesBra = [
Переименовал linkListSubcategoriesBra в braSubcategoryRoutesData

2021-07-12 05:49 UTC, AlecCross commented on src/data/LinksToPages/linkListSubcategoriesKnickers.js
> +const linkListSubcategoriesKnickers = [
Переименовал linkListSubcategoriesKnickers в knickersSubcategoryRoutesData

2021-07-12 11:01 UTC, AlecCross commented on src/components/CategoryPages/SalePage.jsx
> +    const MyQuery = gql`
Назвал корректнее "Название компоненты"+"Query"

2021-07-14 08:52 UTC, lifearoundfreaks approved these changes

2021-07-14 08:52 UTC, lifearoundfreaks commented on src/components/Main/MainPage.jsx
> +                <h1 style={{"fontSize": "calc(24px + 16 * (120vw / 1280))", "textAlign": "center"}}>Группы товаров:</h1>
Решили отложить до ПР по дизайну фронта.

2021-07-14 08:54 UTC, merged