Обновил данные о сайте:
feya-bilyzna/feya-bilyzna.github.io pull request #30
Opened 2021-08-12 01:00 UTC by AlecCross

Добавил свою favicon

Назавание, описание, картинку для отображения в телеграме****

closed #23

2021-08-12 13:45 UTC, lifearoundfreaks requested changes
Два вопроса и мелкий коммент.

2021-08-12 13:45 UTC, lifearoundfreaks commented on public/index.html
> -    <meta name="viewport" content="width=device-width, initial-scale=1" />
А почему эти метаданные убираем?

2021-08-12 13:45 UTC, lifearoundfreaks commented on public/manifest.json
> -  "start_url": ".",
Тот же вопрос, нужно ли было убирать эту строку и ниже

2021-08-12 13:45 UTC, lifearoundfreaks commented on public/manifest.json
> -  "short_name": "React App",
Заменить своими данными.

2021-08-13 23:39 UTC, AlecCross reviewed
Коменты к изменениям

2021-08-19 13:34 UTC, lifearoundfreaks commented on public/index.html
> -    <meta name="viewport" content="width=device-width, initial-scale=1" />
https://developer.mozilla.org/ru/docs/Glossary/Viewport

Похоже, что влияет. Почитать на досуге и или оставить, или убрать с хорошим обоснованием.

2021-08-19 13:39 UTC, lifearoundfreaks requested changes

2021-08-19 13:39 UTC, lifearoundfreaks commented on public/index.html
> -    <meta name="viewport" content="width=device-width, initial-scale=1" />
https://developer.mozilla.org/ru/docs/Glossary/Viewport

Похоже, что влияет. Почитать на досуге и или оставить, или убрать с хорошим обоснованием.

2021-08-19 13:39 UTC, lifearoundfreaks commented on public/manifest.json
> -  "short_name": "React App",
"short_name" не  должен совпадать с названием из метатага (судя из примера реакта)? "name" тоже нужно заменить своим, а не просто убрать.

2021-08-20 01:00 UTC, AlecCross commented on public/index.html
> -    <meta name="viewport" content="width=device-width, initial-scale=1" />
Прочёл, для сайтов с адаптивным дизайном рекомендуется использовать: width=device-width.

На практике не удалось заметить проблем. 
Раз рекомендуют,  я не могу описать хорошее обоснование убрать тег viewport

2021-08-20 11:56 UTC, lifearoundfreaks approved these changes

2021-08-20 11:57 UTC, merged