Добавил контактную информацию: ...
feya-bilyzna/feya-bilyzna.github.io pull request #31
Opened 2021-08-12 02:54 UTC by AlecCross

Создал файл с контактными данными и отрисовал их на странице Контактов и на футере

closed #24

2021-08-12 13:50 UTC, lifearoundfreaks commented on src/components/ContactsPage/PopoutContactElements.jsx
> +                            href={contact.link}
Предлагаю просто ссылку, так как пользователь и так будет видеть, куда ведет эта ссылка из заголовка выше.

2021-08-12 13:51 UTC, lifearoundfreaks commented on src/data/contactsData.js
> +        // {
Кажется, в этих комментариях нет нужды.

2021-08-13 23:38 UTC, AlecCross reviewed
Прокоментировал изменения

2021-08-13 23:38 UTC, AlecCross commented on src/components/FooterComponent.jsx
> +            style={{
Этими стилями я пытался в футере создать колонки для контактных данных. Но мне не нравится реализация. Предлагаю для футера не использовать процедурную отрисовку всех данных. А захардкодить только часть из них.

2021-08-13 23:38 UTC, AlecCross commented on src/data/contactsData.js
> +            name: "Telegram",
Начиная отсюда контакты не актуальны, чуть позже когда контакты появятся в наличии, я их актуализирую на сайте. 

Оставил их для демонстрации размещения в футере.

2021-08-19 13:31 UTC, lifearoundfreaks requested changes

2021-08-19 13:31 UTC, lifearoundfreaks commented on src/components/ContactsPage/PopoutContactElements.jsx
> +                            href={contact.link}
Речь шла не об описании а о том, что бы сделать ссылки именно ссылками, а именно url, вместо текста. Так как из надписи выше и так понятно, куда эта ссылка ведет. Нам не подходит это?

2021-08-19 13:31 UTC, lifearoundfreaks commented on src/components/FooterComponent.jsx
> +            style={{
Хорошо

2021-08-19 13:31 UTC, lifearoundfreaks commented on src/data/contactsData.js
> +            name: "Telegram",
Не нужно оставлять в коде неактуальные контакты, даже в виде комментариев. По той простой причине, что в дальнейшем можем передумать, а ничего не делающий код так и останется в проекте.

2021-08-20 00:40 UTC, AlecCross commented on src/components/ContactsPage/PopoutContactElements.jsx
> +                            href={contact.link}
Я показал оба варианта заказчику, выбор пал на такой вид:

![image](https://user-images.githubusercontent.com/49411370/130161346-f9aac67c-5e30-4468-8c30-54e6141d9fe3.png)

Предисловие и гиперссылка

2021-08-20 12:02 UTC, lifearoundfreaks approved these changes

2021-08-20 12:03 UTC, merged