Добавил бесконечную пагинацию на страницы субкатегорий.
feya-bilyzna/feya-bilyzna.github.io pull request #32
Opened 2021-08-17 17:35 UTC by lifearoundfreaks

Нужно хорошо протестировать, могут быть визуальные и не только баги,

Сейчас если прокрутить вниз страницы, то будет отправляться запрос на сервер и выскакивать значок загрузки. Решили, что в этом ПР данное поведение править не будем. Так как апи у нас очень простое и в нем нет возможности узнать, является ли полученная страница последней, нет простого способа изменения данного поведения.

2021-08-20 18:07 UTC, lifearoundfreaks commented on src/components/VisualElements/ProductSubcategoryPage.jsx
> +                        page: data.categoryProducts?.length ?
[Вот этот](https://github.com/feya-bilyzna/feya-bilyzna.github.io/pull/32/commits/4540ef2242a1cb4ecd068f9132c629edf51cad83) коммит, вроде бы, должен исправить эту ситуацию.

2021-08-20 18:49 UTC, AlecCross requested changes
При переходе с категории или главной на субкатегорию, замечено что товары первой страницы дублируются. Однако это происходит не всегда. Чаще это можно наблюдать через инкогнито. 

Также замечен баг, когда окозавшись внизу страницы после перехода, начинают постоянно отправляться запросы на сервер.

2021-08-20 21:40 UTC, lifearoundfreaks commented on src/components/VisualElements/ProductSubcategoryPage.jsx
> +                        page: data.categoryProducts?.length ?
Внесенная правка оказалась ошибочной. [Вот тут](https://github.com/feya-bilyzna/feya-bilyzna.github.io/pull/32/commits/43825d49d65425d510559a76b2f4237fe86f2573) она убирается.

2021-08-20 21:41 UTC, lifearoundfreaks commented
> При переходе с категории или главной на субкатегорию, замечено что товары первой страницы дублируются. Однако это происходит не всегда. Чаще это можно наблюдать через инкогнито.
> 
> Также замечен баг, когда окозавшись внизу страницы после перехода, начинают постоянно отправляться запросы на сервер.

В последнем коммите должен должны быть исправлены обе проблемы. При переходе по страницам страница теперь всегда скроллится вверх.

2021-08-20 22:28 UTC, lifearoundfreaks commented
На данный момент проблема с бесконечными запросами исправлена немного топорно: в случае, если загрузка не происходит, на месте её анимации у нас остается пустой див, что может несколько портить вид страниц.

Проблема заключалась в том, что добавление анимации загрузки увеличивало длину страницы и "триггерило" проверку на скролл, которая в свою очередь запускала новый запрос на сервер, что заново запускало анимацию - так и получался бесконечный цикл.

Если пустая коробка внизу страницы нас не устраивает, вижу три потенциальных решения:

- Отказаться от анимации вовсе.
- Отображать что-нибудь в этом пространстве. Например, сообщение о том, что товары на странице закончились.
- Придумать способ отображать анимацию загрузки, который не будет менять высоту страницы. Например вместо анимации выводить пользователю тост о загрузке новых товаов.

Описанное выше обсудить и по необходимости создать новый ПР.

2021-08-21 12:06 UTC, AlecCross approved these changes
Круто. LGTM

2021-08-21 12:06 UTC, merged