Отобрацение цены, кнопки довавить в избранное на карточке товара (Увеличение места для карточек)
feya-bilyzna/feya-bilyzna.github.io pull request #47
Opened 2021-10-09 07:20 UTC by AlecCross

- Пока кнопка распознает нажатие и меняет иконку, добавлено или не добалено в избранное.

- При наведении на карточку она как бы приподнимается над другими.

- Так же уменьшены отступы между рядами карточек сверху и снизу. 
(Так как добален новый пункт которые удлинят карточку, стоило укоротить растояние между рядами свеху и снизу. До этого оно было неоправдано больше, чем по бокам)

- Заодно на низком разрешении PageContainer занимает 100% между Navbar и Footer - это позволило увеличить карточку в целом. Небольшое расстояние межлу краем окна и PageContainer выглядело личшним и отнимающим итак небольшое пространство у контента 
(На большом и среднем разрешении всё устраивает)

2021-10-09 09:01 UTC, lifearoundfreaks requested changes

2021-10-09 09:01 UTC, lifearoundfreaks commented on src/index.css
> +}
Если не получается обойтись инлайн стилями, все равно не стоит использовать статику, вместо этого лучше использовать [модульные стили](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet).

2021-10-09 09:19 UTC, lifearoundfreaks commented
Если убрать отступ под навбаром осознанное решение, то необходимо убрать данный визуальный баг.
![image](https://user-images.githubusercontent.com/42870020/136652384-03cd204c-f137-4324-a64b-7a5bd884995c.png)

2021-10-10 03:27 UTC, AlecCross commented
Медиазапросы для PageContainer перенесены в файл модульных стилей

2021-10-12 09:42 UTC, lifearoundfreaks requested changes
Комментарии, вопросы.

2021-10-12 09:42 UTC, lifearoundfreaks commented on src/components/PartialElements/Price.jsx
> +        >{remains[0].price ? `${remains[0].price} грн` : noPrice}</div> : <></>:noPrice}
В чем причина этой двойной тернарки и чем нам не подходит более читаемое `remains[0]?.price ? '${remains[0].price} грн' : "Нет цены"`? (' заменить на `, тут их не позволяет форматирование).

2021-10-12 09:42 UTC, lifearoundfreaks commented on src/components/PartialElements/Price.jsx
> +const Price = ({remains}) => {
Брать пропсом remains может оказаться недальновидным решением, если в дальнейшем мы будем извлекать цену из самого товара. Предлагаю принимать в данном компоненте сам товар и уже из него извлекать цену.

Помимо того, вопрос. Реализовывать в компоненте функционал ценового диапазона не стали чисто из лени? Желательно его сделать не столько ради сайта, а чтоб лучше разобраться с языком и API.

2021-10-12 09:42 UTC, lifearoundfreaks commented on src/components/PageContainer.jsx
> +import s from '../css.module/PageContainer.module.css'
Предлагаю заменить `s` на `styles`, `containerStyles` или `pageContainerStyles`

2021-10-12 09:42 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +        {item.remains ?
А зачем нам remains для добавления в избранное?

2021-11-06 01:29 UTC, AlecCross commented
Пердал сам товар вместо remains  и Поправил тернарку в Price.jsx
Remains для добавления в избранное нам не нужен так как мы добавляем весь товар в избранное а не его вариант, я ошибочно проверял его наличие полагая что он пригодится. 

Навбар не трогал более. Так как лучш его править буду в ветке cross/Navbar

Ценовой диапазон не реализовывал потому-то он не нужен для данного магазина. Если попрактиковаться с его реализацией то я за, но не в этом pr

2021-11-06 02:30 UTC, lifearoundfreaks approved these changes
LGTM

2021-11-06 02:39 UTC, lifearoundfreaks requested changes
Новый комментарий и один старый комментарий актуален.

2021-11-06 02:39 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +    console.log(item)
Забыли убрать.

2021-11-06 04:18 UTC, AlecCross commented
удалил вызов консоли.
добавил диапазон цен
изменил проверку на отрисовку кнопки избранного на карточках

2021-11-06 04:39 UTC, lifearoundfreaks approved these changes
LGTM

2021-11-06 04:40 UTC, merged