Cross/sort and filter
feya-bilyzna/feya-bilyzna.github.io pull request #54
Opened 2021-11-13 11:22 UTC by AlecCross

Добавлен блок с фильтрами и сортировкой в подкатегории.

Фильтр по цвету и сортировка по цене общие для всех подкатегорий.

Фильтры по чашке и по обхвату предназначены для бюстгальтеров, так же есть отдельный фильтр трусов по размеру

closed #46

2021-11-13 14:54 UTC, lifearoundfreaks requested changes
Коммантарии + поправить ворнинги.

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/components/PartialElements/filter-sort/Sort.jsx
> +            id="sorts"
Нам нужен тут айди?

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/components/PartialElements/filter-sort/Sort.jsx
> +            value="0"
Это выполняет какую-то роль?

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/components/PartialElements/filter-sort/ProductFilter.jsx
> +const ProductFilter = ({ onChange, label, filterOptions }) => {
Компоненты `Sort ` и `ProductFilter` вышли практически идентичными. Может объединим их в более абстрактную `ProductOptionSelect` (или похожее название)?

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/css.module/FilterSort.module.css
> +
Нужно убрать тут пробелы.

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/components/VisualElements/ProductSubcategoryPage.jsx
> +    const [knickersFilter, setKnickersFilter] = useState()
Во-первых, похоже, что в `refetch` можно не передавать не изменившиеся с прошлого запроса переменные.

Во-вторых, мне кажется, имеет смысл объединить эти четыре стейта в один стейт с объектом, содержащим все четыре фильтра.

Если сейчас делаем так:
```
setColorFilter(event.target.value)
refetch(
    { ...queryVariables, variantStyles: { ...queryVariables.variantStyles, color: event.target.value || undefined } }
)
```
То потом будем делать так:
```
const newFilters = { ...queryVariables.variantStyles, color: event.target.value || undefined }
setFilters(newFilters)
refetch({variantStyles: newFilters})
```

Можно даже написать отдельную функцию, что-бы сократить количество кода:
```
const updateFilters = (filterName, filterValue) => {
    const newFilters = { ...queryVariables.variantStyles, [filterName]: filterValue || undefined }
    setFilters(newFilters)
    refetch({variantStyles: newFilters})
}
```

Не забыть, что нужно будет поменять и `queryVariables` соответствующим образом.

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/components/PartialElements/filter-sort/ProductFilter.jsx
> +                {item.value}
`item.label || item.value`

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/components/PartialElements/filter-sort/ProductFilter.jsx
> +            <option>
Убрать эту опцию, вместо неё будут дефолтные опции в `filterSortData.js`.

2021-11-13 14:54 UTC, lifearoundfreaks commented on src/data/filterSortData.js
> +}
Добавить везде дефолтную опцию `{ value: "", label: "Все" }`.

2021-11-16 11:23 UTC, AlecCross commented
Объединил 5 стейтов в 1 и совместил это с queryVariables

Ворнинг { Line 7:8:  'styles' is defined but never used  no-unused-vars }
связан с тем что css.module использует костыль применяющий глобальные настройки для материалайзовских классов и не используется напрямую ()

2021-11-16 18:23 UTC, lifearoundfreaks commented
> Объединил 5 стейтов в 1 и совместил это с queryVariables
> 
> Ворнинг { Line 7:8: 'styles' is defined but never used no-unused-vars } связан с тем что css.module использует костыль применяющий глобальные настройки для материалайзовских классов и не используется напрямую ()

Обсудили голосом, комментарий не актуален.

2021-11-16 18:29 UTC, lifearoundfreaks requested changes
Новые комментарии и не закрыт один старый + один ворнинг остался.

2021-11-16 18:29 UTC, lifearoundfreaks commented on src/css.module/FilterSort.module.css
> +:global(.collapsible-body) {
Стиль ломает другие части сайта (например контакты).

2021-11-16 18:29 UTC, lifearoundfreaks commented on src/components/PartialElements/SelectorSpecificProducts.jsx
> +const SelectorSpecificProducts = ({onChange, options, label, filter}) => {
Обсудив голосом, решили поменять название.

2021-11-16 18:29 UTC, lifearoundfreaks commented on src/data/filterSortData.js
> +            { value: "white", label: "", link: "https://bn1301files.storage.live.com/y4m9F9GU4zGUyR1YwDUWnXveiR71ITtSZ9SUl4pvc3HVDgkQW7qAlMt5mD0vF6kDjUgFPNsQQDFMszS2FHow6efIdHjuzTeDSnb5ZA7OzFuAr2xSfy
Думаю, есть смысл попробовать реализовать картинки с помощью элемента `:after`. если это окажется возможным.

2021-11-25 20:36 UTC, AlecCross commented
Попробовал реализовать картинки с помощью элемента :after.  но это не возможно. Описал в Issue #58

Убраны картинки цвета, добален русские названия цветов в фильтре цвета 

Добавлен отступ сверху названия блока фильтрации. Это очень нужно.

2021-11-27 17:46 UTC, lifearoundfreaks approved these changes
LGTM

2021-11-27 17:50 UTC, merged