Cross/visual edits
feya-bilyzna/feya-bilyzna.github.io pull request #56
Opened 2021-11-18 15:38 UTC by AlecCross

Добавил иконки возле все товары и возле контактов на навбаре на большом разрешении

Отступы разграничивающие блоки (На главной)

Добавил сообщение "выберите цвет и размер" (Призыв к действию) на DetailPage

Совместил 2 папки css в одну

Close #53

2021-11-20 20:28 UTC, lifearoundfreaks submitted a review, later dismissed
Помимо комментария в коде, просьба подтвердить, что заказчика устраивает внешний вид.
![image](https://user-images.githubusercontent.com/42870020/142740011-bfb18c1a-e229-4299-bf04-4fc8ba3ee8f9.png)
Мне показалось, что на картинке сверху отступы слишком маленькие и стиль таблички с просьбой выбрать вариант выглядит не очень уместно.

2021-11-20 20:28 UTC, lifearoundfreaks commented on src/components/VisualElements/DetailPage.jsx
> +            )}
Много лишнего кода и ненужной вложенности.
Предлагаю переписать следуюшим образом:
- Написать функцию, которая будет принимать аргументом список категорий товара и возвращать список вида `[{name: 'Название категории', route: 'Маршрут категории'}]`.
- По результатам этой функции написать гораздо более простой map, не делающий ничего кроме рендера кнопок.

2021-11-20 20:30 UTC, lifearoundfreaks requested changes
Повторно создаю ревью, так как нечаянно выбрал Approve на предыдущем.

2021-11-21 12:35 UTC, AlecCross commented
Добавил отступ для иконок в 20px
Убрал рамку для "Выберите вариант товара"
На остове советя по рефакторингу кода добавил функцию, которая принимает аргументом список категорий товара и возвращать список вида [{name: 'Название категории', route: 'Маршрут категории'}].
По результатам этой функции описал более простой map, не делающий ничего кроме рендера кнопок "назад к категории"

2021-11-21 12:49 UTC, AlecCross commented
Так как этот pr предназначен для визуальных улучшений впомнил что кнопки выбора размера выбиваются из общего стиля по цвету

- Изменил цвет для кнопок выбора размеров на pink accent-4.

2021-11-21 19:16 UTC, AlecCross commented
![image](https://user-images.githubusercontent.com/49411370/142775799-cd5e0a7d-3802-4dd4-9efc-5dccbf846728.png)
- Призыв к действию для каждого пункта варианта 
- Убрал ворнинги на map() 
- Убрал комментарии
- Немного подровнял блок вариантов чтобы он был в одной плоскости с остальными данными товара. (marginLeft: 0 это так нужно)

2021-11-22 07:11 UTC, lifearoundfreaks requested changes
![image](https://user-images.githubusercontent.com/42870020/142818673-80b47f14-8f2e-4338-a791-9fbfe748b968.png)
Кроме комментариев, тут наблюдается визуальная разница в 4 пикселя.

2021-11-22 07:11 UTC, lifearoundfreaks commented on src/components/VisualElements/DetailPage.jsx
> +    }
- Похоже, опечатка: categoriesNameRout`е`List. Помимо того, название функции не очень очевидное. Услышав случайно в разговоре его понял бы, что она делает? Предлагаю `findParentCategories` или что-то похожее.
- В данном коде есть ненужные циклы в циклах. Можно вместо этой вложенности сначала создать `Set` из списка имен категорий товара и затем проверять наличие имени проверяемой категории в этом сете с помощью функции `.has()`. Подробнее [тут](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Set/has).
- list плохое название для переменной, предлагаю и вовсе от неё отказаться и возвращать данные вот так:
```
return [
    ...stuff1.map(someFunction),
    ...stuff2.map(someFunction),
]
```
- Для уменьшения количества кода можно не выковыривать в новый объект `name` и `route`, а просто передавать объект в исходном состоянии (вместо `{ name: uncategorizedSubcategory.name, route: uncategorizedSubcategory.route }` - `uncategorizedSubcategory`).
- Есть причина, по которой заменили `map` на `forEach`?

2021-11-22 07:11 UTC, lifearoundfreaks commented on src/components/VisualElements/DetailPage.jsx
> +                categoriesNameRoutList(data?.productById.categories).map(productCategoryData => <Fragment key={productCategoryData.route}>
Можем вместо `productCategoryData => ` использовать `({route, name}) => `.

2021-11-22 18:29 UTC, AlecCross commented
Рефакторинг на основе комментариев

В VariantSelectors использован selectorLabel вместо selectorType

Сменил название для функции определения родительской категории для кнопки назад

Убрал ненужные циклы в циклах, так же немного уменьшил код, сменил название списка родительских категорий возвращаемых для отрисовки кнопок назад

При рендере тоже немного сократил код  вместо productCategoryData => использовал ({route, name}) =>

2021-11-25 16:33 UTC, lifearoundfreaks approved these changes
LGTM

2021-11-25 16:34 UTC, merged