Улучшен Navbar:
feya-bilyzna/feya-bilyzna.github.io pull request #7
Opened 2021-06-25 09:42 UTC by AlecCross

Установлен и подключен react-materialize - npm; Работает адаптивно Navbar (Как под desktop так и под mobile); Добавлен Dropdown пункт 'Все товары' и компоненты для пунктов

2021-06-25 14:35 UTC, lifearoundfreaks requested changes
Добавить пустые строки в конце файлов, где их нет.

2021-06-25 14:53 UTC, lifearoundfreaks requested changes

2021-06-25 14:53 UTC, lifearoundfreaks commented on src/components/All-Types-Goods/Brands.jsx
> +const Brands = () => {
Переименовать эту и другие компоненты страниц в ...Page для большей ясности. Например BrandsPage.

2021-06-25 14:53 UTC, lifearoundfreaks commented on src/components/NavbarMenu.jsx
> +           {/*<Navbar*/}
Много закомментированных строк. Лучше не мусорить в проекте, если только в этом нет большой необходимости. Назови хорошие причины оставить закоментированый текст или потри.

Касается и закомментированного кода выше.

2021-06-25 14:53 UTC, lifearoundfreaks commented on src/components/NavbarMenu.jsx
> +                   <li><NavLink to="/brands">Бренды</NavLink></li>
Вижу li, но не вижу ol или ul. Dropdown сам его добавляет? Если нет, добавить.

И еше вопрос. Может стоит переделать NavbarMenu  так, чтоб мы передавали в него список компонент, а он отрисовывал их с помощью map? Хорошие примеры есть [тут](https://ru.reactjs.org/docs/lists-and-keys.html).

2021-06-27 09:50 UTC, AlecCross commented on src/App.css
> +/*.App {*/
Я исследовал вопрос контейнера в материалайзе, и забыл вернуть этот кусок к исходному. 
В этом файле помоему были стили при создании проекта, они не на что не влияют в данном случае. Их вообще можно просто удалить

2021-06-27 09:51 UTC, AlecCross commented on src/App.js
> +import {HashRouter, Footer} from 'react-router-dom'
Тоже задыл всё почистить. Я прикручивал футер, чтобы взглянуть как оно будет выглядить

2021-06-27 16:25 UTC, lifearoundfreaks submitted a review, later dismissed

2021-06-27 16:42 UTC, lifearoundfreaks approved these changes

2021-06-27 16:42 UTC, merged