Отметка на товаре "ПРОДАНО", если его нет в наличии
feya-bilyzna/feya-bilyzna.github.io pull request #87
Opened 2022-04-18 14:05 UTC by AlecCross

![image](https://user-images.githubusercontent.com/49411370/163819673-149d6187-63a6-43f7-b42a-8f3ef6d67576.png)

2022-04-25 23:25 UTC, lifearoundfreaks requested changes

2022-04-25 23:25 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +                <ImageView areAvailable={isSubcategory ? areAvailable(item.remains) : false} image={image} />
https://github.com/feya-bilyzna/feya-bilyzna.github.io/blob/cross/EditCategoryAndSubCategoryPage/src/components/VisualElements/ImageView.jsx#L4

Как наблюдаем, эта компонента не принимает данный проп.

2022-04-25 23:25 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +    const salesStyle = {
Мне кажется, `soldTextStyle` будет более уместно.

2022-04-25 23:25 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +            isSubcategory ? areAvailable(item.remains) ?
Нужна ли двойная тернарка тут? Не проще ли будет использовать логический оператор?

2022-04-25 23:25 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +                >ПРОДАНО</div> : <></> : <></>
Возможно стоит добавить в i18n? К примеру, на случай, если захочется сделать английскую версию.

2022-04-25 23:25 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +            onClick={isSubcategory && areAvailable(item.remains) ? handleClick : null}>
В случае, когда не хотим, чтоб пользователь переходил на товар, лучше вообще не рендерить компонент NavLink. К тому же, на самой карточке при текущей реализации `pointer: cursor`, что нежелательно, так как сбивает с толку.

2022-04-25 23:25 UTC, lifearoundfreaks commented on src/components/CustomMaterialize/CustomCard.js
> +        else return false
В принципе понял логику функции, но она очень не интуитивно (и с выполнением излишних действий) написана.

Предлагаю переписать, используя [reduce](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce). Получиться в итоге все должно в один вызов, без объявления каких либо дополнительных переменных.

2022-04-28 07:36 UTC, AlecCross commented on src/components/CustomMaterialize/CustomCard.js
> +                >ПРОДАНО</div> : <></> : <></>
Если уже и понадобится добавлять английскую версию, то займусь этим словом.

2022-05-01 07:16 UTC, lifearoundfreaks approved these changes

2022-05-01 07:16 UTC, merged